version: 0.2

phases:
  install:
    commands:
      - npm install --loglevel info --prefix serverless
      - npm --version
      - printenv
  build:
    commands:
      - cd serverless; npx sls deploy --region us-east-1; npx sls deploy --region eu-west-1; npx sls deploy --region ap-southeast-1 

artifacts:
  files:
    - './**/*'

cache:
  paths:
    - 'serverless/node_modules/**/*'